### ISSUE TITLE
Automatically update actions to most recent version in workflow files 

### ISSUE THREAD

**Issue by mashehu** [nf-core/ops#20]
I guess we can also use renovate for that?

**Comment by mashehu** [comment]
For all non-pipeline repos please (you can find them here https://github.com/nf-core/website/blob/main/src/config/ignored_repos.yaml)

**Comment by Emiller88** [comment]
We're gonna need https://docs.renovatebot.com/config-presets/#preset-hosting
I've copied two and I think they're already out of sync.

**Comment by Emiller88** [comment]
Switch to https://docs.renovatebot.com/config-presets/#organization-level-presets
